spring.application.name=botanix
server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/botanicax}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

mail.api.url=${MAIL_API_URL:https://api.brevo.com/v3/smtp/email}
mail.api.key=${MAIL_API_KEY:}
mail.from=${MAIL_FROM:botanix.soporte@gmail.com}
mail.from.name=${MAIL_FROM_NAME:Soporte Botanix}